/*******************************************************************************
 * Copyright 2016 Tremolo Security, Inc.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.tremolosecurity.provisioning.objects;
// Generated Apr 7, 2016 3:31:46 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Approvers generated by hbm2java
 */
@Entity
@Table(name = "approvers")
public class Approvers implements java.io.Serializable {

	private int id;
	private String userKey;
	private Set<Approvals> approvalses = new HashSet<Approvals>(0);
	private Set<ApproverAttributes> approverAttributeses = new HashSet<ApproverAttributes>(0);
	private Set<AllowedApprovers> allowedApproverses = new HashSet<AllowedApprovers>(0);

	public Approvers() {
	}

	public Approvers(int id) {
		this.id = id;
	}

	public Approvers(int id, String userKey, Set<Approvals> approvalses, Set<ApproverAttributes> approverAttributeses,
			Set<AllowedApprovers> allowedApproverses) {
		this.id = id;
		this.userKey = userKey;
		this.approvalses = approvalses;
		this.approverAttributeses = approverAttributeses;
		this.allowedApproverses = allowedApproverses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "userKey")
	public String getUserKey() {
		return this.userKey;
	}

	public void setUserKey(String userKey) {
		this.userKey = userKey;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "approvers")
	public Set<Approvals> getApprovalses() {
		return this.approvalses;
	}

	public void setApprovalses(Set<Approvals> approvalses) {
		this.approvalses = approvalses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "approvers")
	public Set<ApproverAttributes> getApproverAttributeses() {
		return this.approverAttributeses;
	}

	public void setApproverAttributeses(Set<ApproverAttributes> approverAttributeses) {
		this.approverAttributeses = approverAttributeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "approvers")
	public Set<AllowedApprovers> getAllowedApproverses() {
		return this.allowedApproverses;
	}

	public void setAllowedApproverses(Set<AllowedApprovers> allowedApproverses) {
		this.allowedApproverses = allowedApproverses;
	}

}
