/*******************************************************************************
 * Copyright 2016 Tremolo Security, Inc.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.tremolosecurity.provisioning.objects;
// Generated Apr 7, 2016 3:31:46 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.ConstraintMode;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuditLogs generated by hbm2java
 */
@Entity
@Table(name = "auditLogs")
public class AuditLogs implements java.io.Serializable {

	private int id;
	private Approvals approvals;
	private AuditLogType auditLogType;
	private Targets targets;
	private Workflows workflows;
	private int isEntry;
	private Users user;
	private String attribute;
	private String val;

	public AuditLogs() {
	}

	public AuditLogs(int id, AuditLogType auditLogType, int isEntry, Users user) {
		this.id = id;
		this.auditLogType = auditLogType;
		this.isEntry = isEntry;
		this.user = user;
	}

	public AuditLogs(int id, Approvals approvals, AuditLogType auditLogType, Targets targets, Workflows workflows,
			int isEntry, Users user, String attribute, String val) {
		this.id = id;
		this.approvals = approvals;
		this.auditLogType = auditLogType;
		this.targets = targets;
		this.workflows = workflows;
		this.isEntry = isEntry;
		this.user = user;
		this.attribute = attribute;
		this.val = val;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, optional = true)
	@JoinColumn(name = "approval" , nullable = true, foreignKey = @ForeignKey(value = ConstraintMode.NO_CONSTRAINT))
	public Approvals getApprovals() {
		return this.approvals;
	}

	public void setApprovals(Approvals approvals) {
		this.approvals = approvals;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "actionType", nullable = false)
	public AuditLogType getAuditLogType() {
		return this.auditLogType;
	}

	public void setAuditLogType(AuditLogType auditLogType) {
		this.auditLogType = auditLogType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "target"  )
	public Targets getTargets() {
		return this.targets;
	}

	public void setTargets(Targets targets) {
		this.targets = targets;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workflow")
	public Workflows getWorkflows() {
		return this.workflows;
	}

	public void setWorkflows(Workflows workflows) {
		this.workflows = workflows;
	}

	@Column(name = "isEntry", nullable = false)
	public int getIsEntry() {
		return this.isEntry;
	}

	public void setIsEntry(int isEntry) {
		this.isEntry = isEntry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Users getUser() {
		return this.user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

	@Column(name = "attribute")
	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	@Column(name = "val")
	public String getVal() {
		return this.val;
	}

	public void setVal(String val) {
		this.val = val;
	}

}
