/*******************************************************************************
 * Copyright 2016 Tremolo Security, Inc.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.tremolosecurity.provisioning.objects;
// Generated Apr 7, 2016 3:31:46 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Workflows generated by hbm2java
 */
@Entity
@Table(name = "workflows")
public class Workflows implements java.io.Serializable {

	private int id;
	private Users users;
	private String name;
	private Date startTs;
	private Date completeTs;
	private String requestReason;
	private Set<AuditLogs> auditLogses = new HashSet<AuditLogs>(0);
	private Set<WorkflowParameters> workflowParameterses = new HashSet<WorkflowParameters>(0);

	public Workflows() {
	}

	public Workflows(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Workflows(int id, Users users, String name, Date startTs, Date completeTs, String requestReason,
			Set<AuditLogs> auditLogses, Set<WorkflowParameters> workflowParameterses) {
		this.id = id;
		this.users = users;
		this.name = name;
		this.startTs = startTs;
		this.completeTs = completeTs;
		this.requestReason = requestReason;
		this.auditLogses = auditLogses;
		this.workflowParameterses = workflowParameterses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startTS", length = 23)
	public Date getStartTs() {
		return this.startTs;
	}

	public void setStartTs(Date startTs) {
		this.startTs = startTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "completeTS", length = 23)
	public Date getCompleteTs() {
		return this.completeTs;
	}

	public void setCompleteTs(Date completeTs) {
		this.completeTs = completeTs;
	}

	@Column(name = "requestReason")
	public String getRequestReason() {
		return this.requestReason;
	}

	public void setRequestReason(String requestReason) {
		this.requestReason = requestReason;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workflows")
	public Set<AuditLogs> getAuditLogses() {
		return this.auditLogses;
	}

	public void setAuditLogses(Set<AuditLogs> auditLogses) {
		this.auditLogses = auditLogses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workflows")
	public Set<WorkflowParameters> getWorkflowParameterses() {
		return this.workflowParameterses;
	}

	public void setWorkflowParameterses(Set<WorkflowParameters> workflowParameterses) {
		this.workflowParameterses = workflowParameterses;
	}

}
