//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.06 at 10:01:59 AM EDT 
//


package com.tremolosecurity.config.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * List of authentication chains
 * 
 * <p>Java class for authChainsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authChainsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dynamicAuthChains" type="{http://www.tremolosecurity.com/tremoloConfig}dynamicPortalUrlsType" minOccurs="0"/>
 *         &lt;element name="chain" type="{http://www.tremolosecurity.com/tremoloConfig}authChainType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authChainsType", propOrder = {
    "dynamicAuthChains",
    "chain"
})
public class AuthChainsType {

    protected DynamicPortalUrlsType dynamicAuthChains;
    protected List<AuthChainType> chain;

    /**
     * Gets the value of the dynamicAuthChains property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicPortalUrlsType }
     *     
     */
    public DynamicPortalUrlsType getDynamicAuthChains() {
        return dynamicAuthChains;
    }

    /**
     * Sets the value of the dynamicAuthChains property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicPortalUrlsType }
     *     
     */
    public void setDynamicAuthChains(DynamicPortalUrlsType value) {
        this.dynamicAuthChains = value;
    }

    /**
     * Gets the value of the chain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthChainType }
     * 
     * 
     */
    public List<AuthChainType> getChain() {
        if (chain == null) {
            chain = new ArrayList<AuthChainType>();
        }
        return this.chain;
    }

}
