//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.22 at 09:24:21 AM EDT 
//


package com.tremolosecurity.config.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * List of authentication mechanisms for this chain
 * 			
 * 
 * <p>Java class for authMechTypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authMechTypes"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dynamicAuthMechs" type="{http://www.tremolosecurity.com/tremoloConfig}dynamicPortalUrlsType" minOccurs="0"/&gt;
 *         &lt;element name="mechanism" type="{http://www.tremolosecurity.com/tremoloConfig}mechanismType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authMechTypes", propOrder = {
    "dynamicAuthMechs",
    "mechanism"
})
public class AuthMechTypes {

    protected DynamicPortalUrlsType dynamicAuthMechs;
    protected List<MechanismType> mechanism;

    /**
     * Gets the value of the dynamicAuthMechs property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicPortalUrlsType }
     *     
     */
    public DynamicPortalUrlsType getDynamicAuthMechs() {
        return dynamicAuthMechs;
    }

    /**
     * Sets the value of the dynamicAuthMechs property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicPortalUrlsType }
     *     
     */
    public void setDynamicAuthMechs(DynamicPortalUrlsType value) {
        this.dynamicAuthMechs = value;
    }

    /**
     * Gets the value of the mechanism property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mechanism property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMechanism().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MechanismType }
     * 
     * 
     */
    public List<MechanismType> getMechanism() {
        if (mechanism == null) {
            mechanism = new ArrayList<MechanismType>();
        }
        return this.mechanism;
    }

}
