//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.22 at 09:24:21 AM EDT 
//


package com.tremolosecurity.config.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tremolosecurity.config.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TremoloConfig_QNAME = new QName("http://www.tremolosecurity.com/tremoloConfig", "tremoloConfig");
    private final static QName _Application_QNAME = new QName("http://www.tremolosecurity.com/tremoloConfig", "application");
    private final static QName _Workflow_QNAME = new QName("http://www.tremolosecurity.com/tremoloConfig", "workflow");
    private final static QName _Reports_QNAME = new QName("http://www.tremolosecurity.com/tremoloConfig", "reports");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tremolosecurity.config.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApplicationsType }
     * 
     */
    public ApplicationsType createApplicationsType() {
        return new ApplicationsType();
    }

    /**
     * Create an instance of {@link TremoloType }
     * 
     */
    public TremoloType createTremoloType() {
        return new TremoloType();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public ApplicationType createApplicationType() {
        return new ApplicationType();
    }

    /**
     * Create an instance of {@link WorkflowType }
     * 
     */
    public WorkflowType createWorkflowType() {
        return new WorkflowType();
    }

    /**
     * Create an instance of {@link ReportsType }
     * 
     */
    public ReportsType createReportsType() {
        return new ReportsType();
    }

    /**
     * Create an instance of {@link ProxyType }
     * 
     */
    public ProxyType createProxyType() {
        return new ProxyType();
    }

    /**
     * Create an instance of {@link UrlType }
     * 
     */
    public UrlType createUrlType() {
        return new UrlType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link ParamWithValueType }
     * 
     */
    public ParamWithValueType createParamWithValueType() {
        return new ParamWithValueType();
    }

    /**
     * Create an instance of {@link FilterConfigType }
     * 
     */
    public FilterConfigType createFilterConfigType() {
        return new FilterConfigType();
    }

    /**
     * Create an instance of {@link FilterChainType }
     * 
     */
    public FilterChainType createFilterChainType() {
        return new FilterChainType();
    }

    /**
     * Create an instance of {@link UrlsType }
     * 
     */
    public UrlsType createUrlsType() {
        return new UrlsType();
    }

    /**
     * Create an instance of {@link ConfigType }
     * 
     */
    public ConfigType createConfigType() {
        return new ConfigType();
    }

    /**
     * Create an instance of {@link MechanismType }
     * 
     */
    public MechanismType createMechanismType() {
        return new MechanismType();
    }

    /**
     * Create an instance of {@link ParamListType }
     * 
     */
    public ParamListType createParamListType() {
        return new ParamListType();
    }

    /**
     * Create an instance of {@link AuthMechTypes }
     * 
     */
    public AuthMechTypes createAuthMechTypes() {
        return new AuthMechTypes();
    }

    /**
     * Create an instance of {@link AuthMechType }
     * 
     */
    public AuthMechType createAuthMechType() {
        return new AuthMechType();
    }

    /**
     * Create an instance of {@link AuthMechParamType }
     * 
     */
    public AuthMechParamType createAuthMechParamType() {
        return new AuthMechParamType();
    }

    /**
     * Create an instance of {@link AuthChainType }
     * 
     */
    public AuthChainType createAuthChainType() {
        return new AuthChainType();
    }

    /**
     * Create an instance of {@link AuthChainsType }
     * 
     */
    public AuthChainsType createAuthChainsType() {
        return new AuthChainsType();
    }

    /**
     * Create an instance of {@link ResultType }
     * 
     */
    public ResultType createResultType() {
        return new ResultType();
    }

    /**
     * Create an instance of {@link ResultGroupType }
     * 
     */
    public ResultGroupType createResultGroupType() {
        return new ResultGroupType();
    }

    /**
     * Create an instance of {@link ResultRefType }
     * 
     */
    public ResultRefType createResultRefType() {
        return new ResultRefType();
    }

    /**
     * Create an instance of {@link ResultGroupsType }
     * 
     */
    public ResultGroupsType createResultGroupsType() {
        return new ResultGroupsType();
    }

    /**
     * Create an instance of {@link AzRuleType }
     * 
     */
    public AzRuleType createAzRuleType() {
        return new AzRuleType();
    }

    /**
     * Create an instance of {@link AzRulesType }
     * 
     */
    public AzRulesType createAzRulesType() {
        return new AzRulesType();
    }

    /**
     * Create an instance of {@link CookieConfigType }
     * 
     */
    public CookieConfigType createCookieConfigType() {
        return new CookieConfigType();
    }

    /**
     * Create an instance of {@link TargetType }
     * 
     */
    public TargetType createTargetType() {
        return new TargetType();
    }

    /**
     * Create an instance of {@link TargetAttributeType }
     * 
     */
    public TargetAttributeType createTargetAttributeType() {
        return new TargetAttributeType();
    }

    /**
     * Create an instance of {@link TargetsType }
     * 
     */
    public TargetsType createTargetsType() {
        return new TargetsType();
    }

    /**
     * Create an instance of {@link ProvisioningType }
     * 
     */
    public ProvisioningType createProvisioningType() {
        return new ProvisioningType();
    }

    /**
     * Create an instance of {@link WorkflowTaskListType }
     * 
     */
    public WorkflowTaskListType createWorkflowTaskListType() {
        return new WorkflowTaskListType();
    }

    /**
     * Create an instance of {@link ProvisionType }
     * 
     */
    public ProvisionType createProvisionType() {
        return new ProvisionType();
    }

    /**
     * Create an instance of {@link WorkflowTasksType }
     * 
     */
    public WorkflowTasksType createWorkflowTasksType() {
        return new WorkflowTasksType();
    }

    /**
     * Create an instance of {@link WorkflowsType }
     * 
     */
    public WorkflowsType createWorkflowsType() {
        return new WorkflowsType();
    }

    /**
     * Create an instance of {@link IfNotUserExistsType }
     * 
     */
    public IfNotUserExistsType createIfNotUserExistsType() {
        return new IfNotUserExistsType();
    }

    /**
     * Create an instance of {@link ProvisionMappingType }
     * 
     */
    public ProvisionMappingType createProvisionMappingType() {
        return new ProvisionMappingType();
    }

    /**
     * Create an instance of {@link ProvisionMappingsType }
     * 
     */
    public ProvisionMappingsType createProvisionMappingsType() {
        return new ProvisionMappingsType();
    }

    /**
     * Create an instance of {@link AddGroupType }
     * 
     */
    public AddGroupType createAddGroupType() {
        return new AddGroupType();
    }

    /**
     * Create an instance of {@link ResyncType }
     * 
     */
    public ResyncType createResyncType() {
        return new ResyncType();
    }

    /**
     * Create an instance of {@link IfAttrHasValueType }
     * 
     */
    public IfAttrHasValueType createIfAttrHasValueType() {
        return new IfAttrHasValueType();
    }

    /**
     * Create an instance of {@link IfAttrExistsType }
     * 
     */
    public IfAttrExistsType createIfAttrExistsType() {
        return new IfAttrExistsType();
    }

    /**
     * Create an instance of {@link AddAttributeType }
     * 
     */
    public AddAttributeType createAddAttributeType() {
        return new AddAttributeType();
    }

    /**
     * Create an instance of {@link TargetConfigType }
     * 
     */
    public TargetConfigType createTargetConfigType() {
        return new TargetConfigType();
    }

    /**
     * Create an instance of {@link MappingType }
     * 
     */
    public MappingType createMappingType() {
        return new MappingType();
    }

    /**
     * Create an instance of {@link IdpType }
     * 
     */
    public IdpType createIdpType() {
        return new IdpType();
    }

    /**
     * Create an instance of {@link IdpsType }
     * 
     */
    public IdpsType createIdpsType() {
        return new IdpsType();
    }

    /**
     * Create an instance of {@link TrustType }
     * 
     */
    public TrustType createTrustType() {
        return new TrustType();
    }

    /**
     * Create an instance of {@link TrustsType }
     * 
     */
    public TrustsType createTrustsType() {
        return new TrustsType();
    }

    /**
     * Create an instance of {@link IdpMappingType }
     * 
     */
    public IdpMappingType createIdpMappingType() {
        return new IdpMappingType();
    }

    /**
     * Create an instance of {@link ApprovalType }
     * 
     */
    public ApprovalType createApprovalType() {
        return new ApprovalType();
    }

    /**
     * Create an instance of {@link ApprovalDBType }
     * 
     */
    public ApprovalDBType createApprovalDBType() {
        return new ApprovalDBType();
    }

    /**
     * Create an instance of {@link ListType }
     * 
     */
    public ListType createListType() {
        return new ListType();
    }

    /**
     * Create an instance of {@link CallWorkflowType }
     * 
     */
    public CallWorkflowType createCallWorkflowType() {
        return new CallWorkflowType();
    }

    /**
     * Create an instance of {@link NotifyUserType }
     * 
     */
    public NotifyUserType createNotifyUserType() {
        return new NotifyUserType();
    }

    /**
     * Create an instance of {@link CustomTaskType }
     * 
     */
    public CustomTaskType createCustomTaskType() {
        return new CustomTaskType();
    }

    /**
     * Create an instance of {@link DeleteType }
     * 
     */
    public DeleteType createDeleteType() {
        return new DeleteType();
    }

    /**
     * Create an instance of {@link OrgType }
     * 
     */
    public OrgType createOrgType() {
        return new OrgType();
    }

    /**
     * Create an instance of {@link QueueConfigType }
     * 
     */
    public QueueConfigType createQueueConfigType() {
        return new QueueConfigType();
    }

    /**
     * Create an instance of {@link PortalUrlType }
     * 
     */
    public PortalUrlType createPortalUrlType() {
        return new PortalUrlType();
    }

    /**
     * Create an instance of {@link PortalUrlsType }
     * 
     */
    public PortalUrlsType createPortalUrlsType() {
        return new PortalUrlsType();
    }

    /**
     * Create an instance of {@link SchedulingType }
     * 
     */
    public SchedulingType createSchedulingType() {
        return new SchedulingType();
    }

    /**
     * Create an instance of {@link ScheduleDBType }
     * 
     */
    public ScheduleDBType createScheduleDBType() {
        return new ScheduleDBType();
    }

    /**
     * Create an instance of {@link JobType }
     * 
     */
    public JobType createJobType() {
        return new JobType();
    }

    /**
     * Create an instance of {@link CronScheduleType }
     * 
     */
    public CronScheduleType createCronScheduleType() {
        return new CronScheduleType();
    }

    /**
     * Create an instance of {@link MessageListenersType }
     * 
     */
    public MessageListenersType createMessageListenersType() {
        return new MessageListenersType();
    }

    /**
     * Create an instance of {@link MessageListenerType }
     * 
     */
    public MessageListenerType createMessageListenerType() {
        return new MessageListenerType();
    }

    /**
     * Create an instance of {@link ReportType }
     * 
     */
    public ReportType createReportType() {
        return new ReportType();
    }

    /**
     * Create an instance of {@link EscalationType }
     * 
     */
    public EscalationType createEscalationType() {
        return new EscalationType();
    }

    /**
     * Create an instance of {@link EscalationPolicyType }
     * 
     */
    public EscalationPolicyType createEscalationPolicyType() {
        return new EscalationPolicyType();
    }

    /**
     * Create an instance of {@link EscalationFailureType }
     * 
     */
    public EscalationFailureType createEscalationFailureType() {
        return new EscalationFailureType();
    }

    /**
     * Create an instance of {@link CustomAzRuleType }
     * 
     */
    public CustomAzRuleType createCustomAzRuleType() {
        return new CustomAzRuleType();
    }

    /**
     * Create an instance of {@link CustomAzRulesType }
     * 
     */
    public CustomAzRulesType createCustomAzRulesType() {
        return new CustomAzRulesType();
    }

    /**
     * Create an instance of {@link DynamicWorkflowType }
     * 
     */
    public DynamicWorkflowType createDynamicWorkflowType() {
        return new DynamicWorkflowType();
    }

    /**
     * Create an instance of {@link AuthLockoutType }
     * 
     */
    public AuthLockoutType createAuthLockoutType() {
        return new AuthLockoutType();
    }

    /**
     * Create an instance of {@link DynamicPortalUrlsType }
     * 
     */
    public DynamicPortalUrlsType createDynamicPortalUrlsType() {
        return new DynamicPortalUrlsType();
    }

    /**
     * Create an instance of {@link ApplicationsType.ErrorPage }
     * 
     */
    public ApplicationsType.ErrorPage createApplicationsTypeErrorPage() {
        return new ApplicationsType.ErrorPage();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TremoloType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TremoloType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.tremolosecurity.com/tremoloConfig", name = "tremoloConfig")
    public JAXBElement<TremoloType> createTremoloConfig(TremoloType value) {
        return new JAXBElement<TremoloType>(_TremoloConfig_QNAME, TremoloType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ApplicationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.tremolosecurity.com/tremoloConfig", name = "application")
    public JAXBElement<ApplicationType> createApplication(ApplicationType value) {
        return new JAXBElement<ApplicationType>(_Application_QNAME, ApplicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkflowType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WorkflowType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.tremolosecurity.com/tremoloConfig", name = "workflow")
    public JAXBElement<WorkflowType> createWorkflow(WorkflowType value) {
        return new JAXBElement<WorkflowType>(_Workflow_QNAME, WorkflowType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReportsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ReportsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.tremolosecurity.com/tremoloConfig", name = "reports")
    public JAXBElement<ReportsType> createReports(ReportsType value) {
        return new JAXBElement<ReportsType>(_Reports_QNAME, ReportsType.class, null, value);
    }

}
