//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.27 at 07:17:00 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tremolosecurity.com/tremoloConfig", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tremolosecurity.config.xml;
