//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 08:46:42 PM EST 
//


package com.tremolosecurity.config.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Top level provisioning configuration
 * 
 * <p>Java class for provisioningType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="provisioningType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="targets" type="{http://www.tremolosecurity.com/tremoloConfig}targetsType"/&gt;
 *         &lt;element name="workflows" type="{http://www.tremolosecurity.com/tremoloConfig}workflowsType"/&gt;
 *         &lt;element name="approvalDB" type="{http://www.tremolosecurity.com/tremoloConfig}approvalDBType" minOccurs="0"/&gt;
 *         &lt;element name="org" type="{http://www.tremolosecurity.com/tremoloConfig}orgType"/&gt;
 *         &lt;element name="queueConfig" type="{http://www.tremolosecurity.com/tremoloConfig}queueConfigType" minOccurs="0"/&gt;
 *         &lt;element name="portal" type="{http://www.tremolosecurity.com/tremoloConfig}portalUrlsType" minOccurs="0"/&gt;
 *         &lt;element name="scheduler" type="{http://www.tremolosecurity.com/tremoloConfig}schedulingType" minOccurs="0"/&gt;
 *         &lt;element name="listeners" type="{http://www.tremolosecurity.com/tremoloConfig}messageListenersType" minOccurs="0"/&gt;
 *         &lt;element name="reports" type="{http://www.tremolosecurity.com/tremoloConfig}reportsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "provisioningType", propOrder = {
    "targets",
    "workflows",
    "approvalDB",
    "org",
    "queueConfig",
    "portal",
    "scheduler",
    "listeners",
    "reports"
})
public class ProvisioningType {

    @XmlElement(required = true)
    protected TargetsType targets;
    @XmlElement(required = true)
    protected WorkflowsType workflows;
    protected ApprovalDBType approvalDB;
    @XmlElement(required = true)
    protected OrgType org;
    protected QueueConfigType queueConfig;
    protected PortalUrlsType portal;
    protected SchedulingType scheduler;
    protected MessageListenersType listeners;
    protected ReportsType reports;

    /**
     * Gets the value of the targets property.
     * 
     * @return
     *     possible object is
     *     {@link TargetsType }
     *     
     */
    public TargetsType getTargets() {
        return targets;
    }

    /**
     * Sets the value of the targets property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetsType }
     *     
     */
    public void setTargets(TargetsType value) {
        this.targets = value;
    }

    /**
     * Gets the value of the workflows property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowsType }
     *     
     */
    public WorkflowsType getWorkflows() {
        return workflows;
    }

    /**
     * Sets the value of the workflows property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowsType }
     *     
     */
    public void setWorkflows(WorkflowsType value) {
        this.workflows = value;
    }

    /**
     * Gets the value of the approvalDB property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalDBType }
     *     
     */
    public ApprovalDBType getApprovalDB() {
        return approvalDB;
    }

    /**
     * Sets the value of the approvalDB property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalDBType }
     *     
     */
    public void setApprovalDB(ApprovalDBType value) {
        this.approvalDB = value;
    }

    /**
     * Gets the value of the org property.
     * 
     * @return
     *     possible object is
     *     {@link OrgType }
     *     
     */
    public OrgType getOrg() {
        return org;
    }

    /**
     * Sets the value of the org property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgType }
     *     
     */
    public void setOrg(OrgType value) {
        this.org = value;
    }

    /**
     * Gets the value of the queueConfig property.
     * 
     * @return
     *     possible object is
     *     {@link QueueConfigType }
     *     
     */
    public QueueConfigType getQueueConfig() {
        return queueConfig;
    }

    /**
     * Sets the value of the queueConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueueConfigType }
     *     
     */
    public void setQueueConfig(QueueConfigType value) {
        this.queueConfig = value;
    }

    /**
     * Gets the value of the portal property.
     * 
     * @return
     *     possible object is
     *     {@link PortalUrlsType }
     *     
     */
    public PortalUrlsType getPortal() {
        return portal;
    }

    /**
     * Sets the value of the portal property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortalUrlsType }
     *     
     */
    public void setPortal(PortalUrlsType value) {
        this.portal = value;
    }

    /**
     * Gets the value of the scheduler property.
     * 
     * @return
     *     possible object is
     *     {@link SchedulingType }
     *     
     */
    public SchedulingType getScheduler() {
        return scheduler;
    }

    /**
     * Sets the value of the scheduler property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedulingType }
     *     
     */
    public void setScheduler(SchedulingType value) {
        this.scheduler = value;
    }

    /**
     * Gets the value of the listeners property.
     * 
     * @return
     *     possible object is
     *     {@link MessageListenersType }
     *     
     */
    public MessageListenersType getListeners() {
        return listeners;
    }

    /**
     * Sets the value of the listeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageListenersType }
     *     
     */
    public void setListeners(MessageListenersType value) {
        this.listeners = value;
    }

    /**
     * Gets the value of the reports property.
     * 
     * @return
     *     possible object is
     *     {@link ReportsType }
     *     
     */
    public ReportsType getReports() {
        return reports;
    }

    /**
     * Sets the value of the reports property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportsType }
     *     
     */
    public void setReports(ReportsType value) {
        this.reports = value;
    }

}
