/*
Copyright 2015 Tremolo Security, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


package com.tremolosecurity.provisioning.sharepoint.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-14T12:04:57.288-04:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "UserGroup", 
                  wsdlLocation = "/home/mlb/workspace-x1/Sharepoint2007Api/wsdl/usergroup.asmx?wsdl",
                  targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/") 
public class UserGroup extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://schemas.microsoft.com/sharepoint/soap/directory/", "UserGroup");
    public final static QName UserGroupSoap = new QName("http://schemas.microsoft.com/sharepoint/soap/directory/", "UserGroupSoap");
    public final static QName UserGroupSoap12 = new QName("http://schemas.microsoft.com/sharepoint/soap/directory/", "UserGroupSoap12");
    static {
        URL url = UserGroup.class.getResource("/home/mlb/workspace-x1/Sharepoint2007Api/wsdl/usergroup.asmx?wsdl");
        if (url == null) {
            url = UserGroup.class.getClassLoader().getResource("/home/mlb/workspace-x1/Sharepoint2007Api/wsdl/usergroup.asmx?wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(UserGroup.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/home/mlb/workspace-x1/Sharepoint2007Api/wsdl/usergroup.asmx?wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public UserGroup(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserGroup(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserGroup() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserGroup(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserGroup(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserGroup(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UserGroupSoap
     */
    @WebEndpoint(name = "UserGroupSoap")
    public UserGroupSoap getUserGroupSoap() {
        return super.getPort(UserGroupSoap, UserGroupSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserGroupSoap
     */
    @WebEndpoint(name = "UserGroupSoap")
    public UserGroupSoap getUserGroupSoap(WebServiceFeature... features) {
        return super.getPort(UserGroupSoap, UserGroupSoap.class, features);
    }
    /**
     *
     * @return
     *     returns UserGroupSoap
     */
    @WebEndpoint(name = "UserGroupSoap12")
    public UserGroupSoap getUserGroupSoap12() {
        return super.getPort(UserGroupSoap12, UserGroupSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserGroupSoap
     */
    @WebEndpoint(name = "UserGroupSoap12")
    public UserGroupSoap getUserGroupSoap12(WebServiceFeature... features) {
        return super.getPort(UserGroupSoap12, UserGroupSoap.class, features);
    }

}
