apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: trusts.openunison.tremolo.io
spec:
  group: openunison.tremolo.io
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: trusts
    singular: trust
    kind: Trust
    shortNames:
    - trust
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            clientId:
              type: string
            clientSecret:
              type: object
              properties:
                secretName:
                  type: string
                keyName:
                  type: string
            publicEndpoint:
              type: boolean
            redirectURI:
              type: array
              items:
                type: string
            codeLastMileKeyName:
              type: string
            authChainName:
              type: string
            codeTokenSkewMilis:
              type: integer
            accessTokenTimeToLive:
              type: integer
            accessTokenSkewMillis:
              type: integer
            signedUserInfo:
              type: boolean
            verifyRedirect:
              type: boolean
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: openunison
  name: openunison-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openunison-secrets
  namespace: openunison
subjects:
- kind: ServiceAccount
  name: openunison-orchestra
  namespace: openunison
roleRef:
  kind: Role
  name: openunison-secrets
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: portalurls.openunison.tremolo.io
spec:
  group: openunison.tremolo.io
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: portalurls
    singular: portalurl
    kind: PortalUrl
    shortNames:
    - portalurl
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            label:
              type: string
            url:
              type: string
            org:
              type: string
            icon:
              type: string
            azRules:
              type: array
              items:
                type: object
                properties:
                  scope:
                    type: string
                  constraint:
                    type: string
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: openunison
  name: openunison-trusts-get
rules:
- apiGroups: ["openunison.tremolo.io"]
  resources: ["trusts","portalurls"]
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openunison-trusts-get
  namespace: openunison
subjects:
- kind: ServiceAccount
  name: openunison-orchestra
  namespace: openunison
roleRef:
  kind: Role
  name: openunison-trusts-get
  apiGroup: rbac.authorization.k8s.io